# Generated by Django 4.2 on 2023-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('body', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='news/')),
                ('short_description', models.CharField(max_length=255)),
            ],
        ),
    ]
