# Generated by Django 4.2 on 2023-04-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='deascription',
            new_name='description',
        ),
    ]
