# Generated by Django 4.2 on 2023-04-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_alter_announcement_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
