# Generated by Django 4.2 on 2023-04-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_alter_announcement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='announcementphoto',
            name='image',
            field=models.ImageField(upload_to='announcementImages/'),
        ),
    ]
