# Generated by Django 4.2 on 2023-04-18 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=255)),
                ('adress_type', models.CharField(choices=[('hostel', 'Хостел/Приют'), ('clinic', 'Ветклиника'), ('zooshop', 'Зоомагазин')], max_length=50)),
                ('verified_adress', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
