# Generated by Django 4.2 on 2023-05-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='catalog',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='schedule',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='catalog',
            name='social_media',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='catalog',
            name='web_site',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
